# Generated by Django 5.1.3 on 2024-11-19 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='almacen',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
    ]
